### ISSUE TITLE
Retrieve last-modified time of disposition code list

### ISSUE THREAD

**Issue by hannahwhy** [NUARIG/ncs_mdes#25]
NCS Navigator Cases' `GET /api/v1/code_lists` service supports conditional get.  It will eventually have to return serialized versions of `NcsNavigator::Mdes::DispositionCode` objects.

To satisfy the `DispositionCode` requirement whilst continuing to support conditional get, I'd like to have a way to determine the last-modified time of the disposition code collection.  (Modification date of the entire MDES would be fine, but might be more difficult than necessary -- AFAICT, the MDES data is spread across several files.)

I was thinking along these lines:

``` ruby
module NcsNavigator::Mdes
  class DispositionCode
    def self.last_modified
      # returns a Time
    end
  end
end
```

That'd lead to a convenient expression in Cases:

``` ruby
class FieldCodeCollection
  include NcsNavigator::Mdes

  def last_modified
    [NcsCode.last_modified, DispositionCode.last_modified].max
  end
end
```

Thoughts?

**Comment by hannahwhy** [comment]
One problem with the `self.last_modified` formulation is that `DispositionCode` currently doesn't have any references to its source.  I'm not sure if it should.

Also, `DispositionCode` is marked as representing "one dispostion code in the MDES", and I'm not too keen on ActiveRecord-style member/collection munging if said munging doesn't already exist.

**Comment by 1samhicks** [comment]
Why do we want to have conditional get? Is the size of the download that large? Isn't it dwarfed by other sync files?

**Comment by hannahwhy** [comment]
Could be.  I haven't measured.

However, there's no point in doing work to regenerate code lists if they haven't updated, and the mechanism is non-invasive.

**Comment by rsutphin** [comment]
There's not a natural value to use for the disposition codes' last modified date. MDES versions don't really have a date (there are dates in some of the documents, but they are not consistently updated) and even if they did, it would be possible for us to need to correct the codes for a given MDES version (e.g., if there was a bug in the way we extracted them).

The one thing I can guarantee that will correspond to a given set of disposition codes in this gem is the ncs_mdes gem version itself. To turn the gem version into a time for `last_modified`, it may be possible to extract a release timestamp from the gem metadata. That has two drawbacks to consider:
- Such a "last modified" time would reflect modifications to the entire gem, not to any one MDES version's disposition codes. It would trigger updates from field more frequently than the perfect solution.
- While extracting a release time from the gem metadata seems doable for an actual released version, I am skeptical that it would work if we were using bundler to depend on a git pre-release version.

The latter is an uncommon case — I tend to release this gem immediately whenever anything changes in it — but the frequent releases amplify the former problem.

**Comment by hannahwhy** [comment]
Disposition codes are read from a YAML file; are the timestamps on those files reliable enough to use?

**Comment by rsutphin** [comment]
The YAML files are part of this gem. It does not appear that file modification timestamps are preserved on gem installs. What you'd be getting is the date that the gem was installed for the client application.

From my local checkout of the gem:

```
$ ls -al ~/ncs/git/mdes/documents/3.0/
total 7808
drwxr-xr-x   6 rsutphin  admin      204 Sep 14 00:40 ./
drwxr-xr-x  10 rsutphin  admin      340 Nov  2 15:02 ../
-rw-r--r--@  1 rsutphin  admin  3901239 Sep 13 16:04 NCS_Transmission_Schema_3.0.00.09.xsd
-rw-r--r--   1 rsutphin  admin    74674 Jun 14 23:16 disposition_codes.yml
-rw-r--r--   1 rsutphin  admin     1893 Jun 14 23:16 extract_disposition_codes.rb
-rw-r--r--   1 rsutphin  admin    10732 Sep 14 00:40 heuristic_overrides.yml
```

From an installed copy:

```
$ ls -al /Users/rsutphin/.rvm/gems/ruby-1.9.3-p194\@ncs_navigator_core/gems/ncs_mdes-0.10.0/documents/3.0
total 7808
drwxr-xr-x  6 rsutphin  admin      204 Sep 18 01:19 ./
drwxr-xr-x  8 rsutphin  admin      272 Sep 18 01:19 ../
-rw-r--r--  1 rsutphin  admin  3901239 Sep 18 01:19 NCS_Transmission_Schema_3.0.00.09.xsd
-rw-r--r--  1 rsutphin  admin    74674 Sep 18 01:19 disposition_codes.yml
-rw-r--r--  1 rsutphin  admin     1893 Sep 18 01:19 extract_disposition_codes.rb
-rw-r--r--  1 rsutphin  admin    10732 Sep 18 01:19 heuristic_overrides.yml
```

The date the gem was installed on the (e.g.) app server may be sufficient for Cases' purposes. However, I would not call it a meaningful "last modified" date for the information in this gem. So I wouldn't be inclined to add the proposed `last_modified` accessor to this gem if it were to be implemented that way.

Note that `Specification#source_documents` will give you a path to the disposition codes' YAML file, so you may do what you need to it directly in Cases.

**Comment by hannahwhy** [comment]
The last-modified time of the YAML file is probably good enough for Cases.

Also, we're already extending DispositionCode in Cases, so the precedent for this sort of thing already exists.  I think that'll be an acceptable solution.
